FROM python:3.12.2-alpine3.20 
#IMAGE 1 RESERVED FOR TP
ARG BUILD_DATE = "20226-19-02"
ARG VERSION = 1.0.0
ARG REQUIREMENTS="requirements.txt"

LABEL org.opencontainers.authors="Lefki Meidi <m.lef3105@gmail.com>"
LABEL org.opencontainers.image.version=$VERSION
LABEL org.opencontainers.image.created=$BUILD_DATE
LABEL org.opencontainers.source="https://github.com/MeidiLprog/MLOPS-DOCKER.git"
LABEL org.opencontainers.description="Over complicating things for my own amusement"

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1


RUN apk add --no-cache wget
RUN apk add --no-cache build-base libffi-dev

WORKDIR /app

COPY ${REQUIREMENTS} .

RUN python -m pip install --no-cache-dir -r ${REQUIREMENTS}
COPY . .

EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=5s --start-period=3s --retries=3 \
        CMD wget -qO- http://localhost:5000/ || exit 1

CMD ["python","main.py"]











